# Generated by Django 5.0.6 on 2024-05-29 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idVehiculo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Id vehiculo')),
                ('marca', models.CharField(blank=True, max_length=40, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=40, verbose_name='Modelo')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
