# Generated by Django 5.0.6 on 2024-06-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehiculo_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Producto',
        ),
    ]
