# Generated by Django 5.0.6 on 2024-06-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_vehiculo_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idVehiculo',
            new_name='idProducto',
        ),
    ]
