# Generated by Django 5.0.6 on 2024-06-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalles',
            field=models.CharField(blank=True, max_length=40, verbose_name='Detalles'),
        ),
    ]
