# Generated by Django 5.0.6 on 2024-06-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='detalles',
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=40, verbose_name='Caracteristicas'),
        ),
    ]
