# Generated by Django 5.0.6 on 2024-06-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_producto_detalles_producto_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caracteristicas'),
        ),
    ]
