# Generated by Django 5.0.6 on 2024-06-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
