# Generated by Django 5.0.6 on 2024-06-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='detalle_boleta',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
