# Generated by Django 5.0.6 on 2024-06-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_boleta_estado_boleta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Id Producto'),
        ),
    ]
