# Generated by Django 5.0.6 on 2024-06-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_producto_idproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caracteristicas',
        ),
    ]
