# Generated by Django 5.0.6 on 2024-07-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_producto_marca_alter_producto_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
    ]
