# Generated by Django 5.0.6 on 2024-07-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalle',
            field=models.CharField(blank=True, max_length=40, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Detalle'),
        ),
    ]
